# Generated by Django 4.2.6 on 2023-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('activee', 'active'), ('blocked', 'blocked')], default='activee', max_length=20),
        ),
    ]
