# Generated by Django 4.2.6 on 2023-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(choices=[('active', 'active'), ('active', 'blocked')], default='active', max_length=20),
        ),
    ]
