# Generated by Django 4.2.6 on 2023-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_customuser_status_customuser_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('BLOCKED', 'blocked')], default='ACTIVE', max_length=20),
        ),
    ]
